### ISSUE TITLE
Back of card no longer displaying properly... Toggles showing up on the front of the card (also with bullet); Back info not fully revealed by default

### ISSUE THREAD

**Issue by 22-modifier** [2anki/2anki.net#1059]
**Describe the bug**
Usually the text from the toggle just populates on the front of the card. Now I'm getting a bullet (that isn't there in Notion as well as the full toggle itself showing up in Anki). If there are multiple lines on the back of the card, then most of it isn't visible, unless you open the toggle from the question (front text).

**To Reproduce**
Just creating deck. Debug report below. 

**Expected behavior**
Shouldn't have the toggle show up (or the bullet).

**Screenshots**

Notion:
<img width="708" alt="Screenshot 2023-02-23 at 10 19 04 PM" src="https://user-images.githubusercontent.com/63695573/221084222-564c6100-2e83-4f8c-807e-49b64efb45a9.png">
Front: (toggle shouldn't be there)
<img width="640" alt="Screenshot 2023-02-23 at 10 19 51 PM" src="https://user-images.githubusercontent.com/63695573/221084234-628f4bf8-016a-4dd9-b8e7-ad9443d6f9dc.png">

Back side (note that most of the information isn't visible):
<img width="639" alt="Screenshot 2023-02-23 at 10 19 59 PM" src="https://user-images.githubusercontent.com/63695573/221084275-58d43d7f-0d94-43dd-862e-0620e8053a28.png">

Back of card, toggle from front expanded reveals all info:
<img width="636" alt="Screenshot 2023-02-23 at 10 20 08 PM" src="https://user-images.githubusercontent.com/63695573/221084327-7966f5dc-8f1c-4bce-92f3-e10decaff9c4.png">

Bullets showing up inappropriately (only happens in Safari):
<img width="712" alt="Screenshot 2023-02-23 at 9 55 02 PM" src="https://user-images.githubusercontent.com/63695573/221080666-b6b8d7ea-8e7a-421a-b9ea-658283980890.png">

<img width="638" alt="Screenshot 2023-02-23 at 9 42 46 PM" src="https://user-images.githubusercontent.com/63695573/221080132-c4931184-2f8d-47f0-99ec-64d498d6f8db.png">

<img width="636" alt="Screenshot 2023-02-23 at 9 42 53 PM" src="https://user-images.githubusercontent.com/63695573/221080120-96fafa71-c4c1-4e7b-825c-7cb387a8df01.png">

**Debug report**
localStorage.setItem(add-notion-link, "true");
localStorage.setItem(reversed, "false");
localStorage.setItem(use-notion-id, "true");
localStorage.setItem(paragraph, "false");
localStorage.setItem(avocado, "true");
localStorage.setItem(enable-input, "false");
localStorage.setItem(tags, "true");
localStorage.setItem(no-underline, "false");
localStorage.setItem(basic-reversed, "false");
localStorage.setItem(cloze, "true");
localStorage.setItem(all, "false");
localStorage.setItem(remove-mp3-links, "true");
localStorage.setItem(perserve-newlines, "true");
localStorage.setItem(max-one-toggle-per-card, "true");
localStorage.setItem(cherry, "false");
localStorage.setItem(google_adsense_settings, "{\"ca-pub-9593032741719801\":[\"ca-pub-9593032741719801\",[],[]]}");
localStorage.setItem(google_experiment_mod44, "129");
localStorage.setItem(email, "trippleavitt@gmail.com");
localStorage.setItem(google_ama_config, "[[[[null,0,null,[],null,null,\"BODY\"],2,[\"10px\",\"10px\",true],[4],null,[],[],1,[],[],[]],[[null,2,null,[],null,null,\"DIV#root>DIV.sc-cOFTSb.jNsPnf>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.sc-iqcoie.hMiKAx.section>DIV.container>DIV.columns>DIV.column\"],3,[\"10px\",\"10px\",true],[0],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-cOFTSb.jNsPnf>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.section.has-background-white>DIV.container>DIV.columns>DIV.sc-hHLeRK.gjUUN.column\"],3,[\"8px\",\"32px\",true],[0],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.kpkelA>DIV.sc-lbxAil.cBznYD\"],4,[\"16px\",\"10px\",true],[4],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV.container>DIV.columns.is-centered\"],4,[\"10px\",\"10px\",true],[3],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>FOOTER.sc-iTONeN.igyPWI>DIV.columns\"],1,[\"10px\",\"10px\",true],[3],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>FOOTER.sc-iTONeN.igyPWI>DIV.columns\"],4,[\"10px\",\"12px\",true],[3],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV.container>DIV.columns.is-centered>DIV.column.is-half>DIV.notification.is-info.column.is-light\"],1,[\"16px\",\"10px\",true],[0],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV.container>DIV.columns.is-centered>DIV.column.is-half>DIV.notification.is-info.column.is-light\"],2,[\"10px\",\"10px\",true],[0],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV.container>DIV.columns.is-centered>DIV.column.is-half>DIV.notification.is-info.column.is-light\"],3,[\"10px\",\"10px\",true],[0],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>FOOTER.sc-iTONeN.igyPWI\"],1,[\"10px\",\"10px\",true],[0],null,[],[],1,[],[2,4],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-cOFTSb.jNsPnf>DIV.sc-kgUAyh.ejIXyw>DIV.sc-gKXOVf.kEBptm\"],1,[\"32px\",\"10px\",true],[4],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-cOFTSb.jNsPnf>DIV.sc-kgUAyh.ejIXyw>DIV.sc-gKXOVf.kEBptm>DIV.sc-hKMtZM.sc-kDDrLX.kpkelA.jfuFbG\"],4,[\"10px\",\"10px\",true],[3],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.sc-kgflAQ.hldLNL.section.hero.is-halfheight\"],2,[\"10px\",\"10px\",true],[2],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.section.has-background-white>DIV.container\"],1,[\"10px\",\"10px\",true],[1],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.sc-iqcoie.hMiKAx.section>DIV.container>DIV.sc-fnykZs.ggfojX.columns\"],1,[\"16px\",\"10px\",true],[1],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.sc-iqcoie.hMiKAx.section\"],4,[\"10px\",\"16px\",true],[1],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.section>DIV.columns\"],4,[\"8px\",\"12px\",true],[3],null,[],[],1,[],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-cOFTSb.jNsPnf>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.sc-iqcoie.hMiKAx.section>DIV.container>DIV.columns>DIV.column>DIV.columns.is-flex-direction-column>DIV.column.is-flex\"],4,[\"10px\",\"10px\",true],[0],null,[],[],2,[[\"6eb80fad\",1600,[[\"box-sizing\",\"content-box\"],[\"width\",\"684px\"],[\"height\",\"115px\"],[\"margin\",\"0px 0px 0px 0px\"]],[[\"width\",\"100%\"],[\"height\",\"100%\"],[\"display\",\"inline-block\"]]]],[],[]],[[null,1,null,[],null,null,\"DIV#root>DIV.sc-cOFTSb.jNsPnf>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.sc-iqcoie.hMiKAx.section>DIV.container>DIV.columns>DIV.column>DIV.columns.is-flex-direction-column>DIV.column.is-flex\"],4,[\"10px\",\"10px\",true],[0],null,[],[],2,[[\"72218f54\",1600,[[\"box-sizing\",\"content-box\"],[\"width\",\"684px\"],[\"height\",\"115px\"],[\"margin\",\"0px 0px 0px 0px\"]],[[\"width\",\"100%\"],[\"height\",\"100%\"],[\"display\",\"inline-block\"]]]],[],[]],[[null,2,null,[],null,null,\"DIV#root>DIV.sc-cOFTSb.jNsPnf>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.sc-iqcoie.hMiKAx.section>DIV.container>DIV.columns>DIV.column>DIV.columns.is-flex-direction-column>DIV.column.is-flex\"],4,[\"10px\",\"10px\",true],[0],null,[],[],2,[[\"9a45e758\",1600,[[\"box-sizing\",\"content-box\"],[\"width\",\"684px\"],[\"height\",\"115px\"],[\"margin\",\"0px 0px 0px 0px\"]],[[\"width\",\"100%\"],[\"height\",\"100%\"],[\"display\",\"inline-block\"]]]],[],[]],[[null,0,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.sc-iqcoie.hMiKAx.section>DIV.container>DIV.columns>DIV.column>DIV.columns.is-flex-direction-column>DIV.column.is-flex\"],4,[\"10px\",\"10px\",true],[0],null,[],[],2,[[\"5c6cb7af\",1600,[[\"box-sizing\",\"content-box\"],[\"width\",\"684px\"],[\"height\",\"115px\"],[\"margin\",\"0px 0px 0px 0px\"]],[[\"width\",\"100%\"],[\"height\",\"100%\"],[\"display\",\"inline-block\"]]]],[],[]],[[null,1,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.sc-iqcoie.hMiKAx.section>DIV.container>DIV.columns>DIV.column>DIV.columns.is-flex-direction-column>DIV.column.is-flex\"],4,[\"10px\",\"10px\",true],[0],null,[],[],2,[[\"561adef7\",1600,[[\"box-sizing\",\"content-box\"],[\"width\",\"684px\"],[\"height\",\"115px\"],[\"margin\",\"0px 0px 0px 0px\"]],[[\"width\",\"100%\"],[\"height\",\"100%\"],[\"display\",\"inline-block\"]]]],[],[]],[[null,2,null,[],null,null,\"DIV#root>DIV.sc-kgUAyh.ejIXyw>DIV.sc-hKMtZM.sc-jSMfEi.kpkelA.iDBDMn>SECTION.sc-iqcoie.hMiKAx.section>DIV.container>DIV.columns>DIV.column>DIV.columns.is-flex-direction-column>DIV.column.is-flex\"],4,[\"10px\",\"10px\",true],[0],null,[],[],2,[[\"b712f19c\",1600,[[\"box-sizing\",\"content-box\"],[\"width\",\"684px\"],[\"height\",\"115px\"],[\"margin\",\"0px 0px 0px 0px\"]],[[\"width\",\"100%\"],[\"height\",\"100%\"],[\"display\",\"inline-block\"]]]],[],[]]],[],[1677293065069],\"20230220_093435\",[],[[]],[[null,[],null,\"5004010262\",[],[],[1701676238,1],true,null,null,[]],[null,[],null,\"5004010262\",[],[],[1958768999,2],true,null,null,[]],[null,[1,3,2],null,\"5004010262\",[],[],[0,2],true,null,[1],[]]],[null,[[1,\"1vp\",[[4,\"2vp\",\"2vp\"],[6,\"3vp\",\"3vp\"]],8,\"1vp\",0.30000001,[\"0.2vp\",\"0vp\",2]],[2,\"300px\",[[4,\"600px\",\"600px\"],[6,\"900px\",\"900px\"]],8,\"300px\",0.30000001,[\"60px\",\"0px\",2]]]],null,null,null,null,null,null,[null,null,null,null,null,null,null,null,null,null,null,false,null,null,false,null,null,null,null,null,null,null,null],null,null,null,null,[2122057412],null,null,[1677028483871]]");

**Desktop (please complete the following information):**
 - OS: Mac OS 13.2.1 (22D68)
 - Browser Safari and Chrome
 - Version Anki 2.1.60

**Comment by aalemayhu** [comment]
Thanks for you report but this is now the new default.

**Comment by aalemayhu** [comment]
Reopening after triage: Toggle rendering fidelity is core to Notion-to-Anki conversion; bug closed in 2023 without fix documented.. Reviewed by: pm agent.

**Comment by aalemayhu** [comment]
## Related finding (May 2026)

Part of this issue traces to `removeToggleStructureTags` in `DeckParser.ts` lines 225-233, which strips ALL `<ul>`, `</ul>`, `<li>`, and `</li>` tags unconditionally via regex when `maxOne` is true. This destroys the visual hierarchy of bulleted lists inside toggle backs — nested bullets flatten into a single run of text.

A 2026 support email from a paying subscriber confirms this is still present: bolded list items inside toggles are not treated as section boundaries, and sibling bullets merge into the first list item.

**Fix direction:** `removeToggleStructureTags` should only strip toggle-related structure tags (the outer `<details>/<summary>/<ul class="toggle">`) while preserving inner `<ul>/<li>` tags that represent content hierarchy.

**Comment by aalemayhu** [comment]
This is from 2023 with a description that matches the pre-rewrite toggle-on-front bug. The current toggle handling either keeps the toggle on the front as Basic or converts to Cloze (when toggle content has `<code>` and `cloze-from-toggle-content` is on). I can't reproduce the original symptom. I'm closing this. If a current Notion page still drops the toggle on the front with the back hidden, reopen with the page.
