### ISSUE TITLE
Not able to generate from File to ank format.

### ISSUE THREAD

**Issue by Isimut80** [2anki/2anki.net#1073]
I generate the file from Notion to HTML.
In 2Anki is not to able to generate into anki view.
[Deutsch Englischuuuu.zip](https://github.com/2anki/2anki.net/files/10888476/Deutsch.Englischuuuu.zip)

**Comment by Isimut80** [comment]
![IMG_2137](https://user-images.githubusercontent.com/126942314/222939063-4c26035a-459f-4840-bc8f-56ab420eb5ca.png)
![IMG_2138](https://user-images.githubusercontent.com/126942314/222939065-4e813b72-a996-49ec-9b98-a7ae0bb976ce.png)
![IMG_2139](https://user-images.githubusercontent.com/126942314/222939069-53a00c25-d433-4014-98a8-e2805673ffa5.png)

**Comment by Isimut80** [comment]
Still not possible to convert in to Anki!

**Comment by aalemayhu** [comment]
In the HTML upload, we only **support toggles**. In your example, **you are using bullet points** that won't work in the HTML upload.

**Comment by aalemayhu** [comment]
Second-pass review (pm): TODO/stub found in relevant code - feature not fully implemented

Evidence: node_modules/.pnpm/@anthropic-ai+sdk@0.95.1/node_modules/@anthropic-ai/sdk/src/internal/uploads.ts:173:  // TODO: make n

**Comment by aalemayhu** [comment]
Closing this — stale personal-todo without active user demand pulling it forward. If this becomes load-bearing later, I'll open a fresh, scoped issue.
