### ISSUE TITLE
My notion notes do not convert to anki flashcard

### ISSUE THREAD

**Issue by DanBot13** [2anki/2anki.net#1076]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DanBot13** [comment]
My notion notes do not convert to anki flashcard

**Comment by DanBot13** [comment]
I need my notion notes to convert anki flashcard

**Comment by aalemayhu** [comment]
@DanBot13 please add an example, otherwise it's too time consuming for me too look into.

**Comment by aalemayhu** [comment]
Not enough information
