### ISSUE TITLE
my code tags do not get converted to cloze deletions in anki

### ISSUE THREAD

**Issue by DanBot13** [2anki/2anki.net#1094]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DanBot13** [comment]
![image](https://user-images.githubusercontent.com/127252802/225380348-9accaac1-fd24-4c89-bd62-e18e4e05a966.png)

**Comment by DanBot13** [comment]
![image](https://user-images.githubusercontent.com/127252802/225381736-8cf53dd4-8c3e-4de9-af55-c81935b58bfe.png)
and then when i export, it says this

**Comment by DanBot13** [comment]
![image](https://user-images.githubusercontent.com/127252802/225381817-c5ee3075-84d1-454c-a363-6857b4fcb1a3.png)
not sure which options to use

**Comment by aalemayhu** [comment]
@DanBot13 in your screenshot I can clearly see you are using bullet points. That's not the same as toggles. They are different blocks. Unfortunately in the HTML upload, only **toggles** are supported. So either change them to toggles or use the search feature where you can connect your workspace and use bullet point blocks.

**Comment by aalemayhu** [comment]
I hope my previous message did not sound too harsh, thanks for sharing the screenshots.

**Comment by aalemayhu** [comment]
This will be adressed in #1165

**Comment by aalemayhu** [comment]
Second-pass review (pm): TODO/stub found in relevant code - feature not fully implemented

Evidence: node_modules/.pnpm/@aws-sdk+nested-clients@3.996.21/node_modules/@aws-sdk/nested-clients/dist-types/submodules/sso-oidc/

**Comment by aalemayhu** [comment]
Verified against current main — inline `code` on the front of a toggle now converts to a cloze deletion (`{{c1::…}}`), and multiple code spans each get their own numbered cloze. This is covered by passing tests in `src/lib/parser/helpers/handleClozeDeletions.test.ts` referencing this issue. Closing as fixed. Reopen with a fresh export if you still hit this.

**Comment by aalemayhu** [comment]
Fixed in PR #2444 (commit 0788a98ef03f, merged 2026-05-20): code blocks are now converted to numbered cloze deletions ({{c1::…}}), with test coverage specifically for this case. Closing as resolved — reopen with a sample export if it recurs.
