### ISSUE TITLE
Bring back the 'open in Anki' link

### ISSUE THREAD

**Issue by 0x171-0** [2anki/2anki.net#1124]
**Is your feature request related to a problem? Please describe.**
"I hope 2anki can bring back the 'open in Anki' link. It disappeared recently 😭, which makes it hard to find notes that need to be updated..."

**Describe the solution you'd like**
Add it back to "Card Options"

Thank you.

**Comment by 22-modifier** [comment]
I think I asked about this on the discord and Alex A (developer) mentioned it wasn't stable or something of that nature, so they removed it. But I agree it was one of the most useful features. I have noticed HTML upload being more reliable and can process a greater number of block styles / formatting in the past several months, so I think there's only so much they can work on at a time.

**Comment by aalemayhu** [comment]
The focus now is stabilzing so I have opted for removing any features that cause issues. I will bring it back but after we have resolved some other issues. Unfortunately I have a lot of private notes but will try to make that roadmap more public soon. I will update this issue when it's back.

**Comment by aalemayhu** [comment]
It's back. Please report any issues with the link as new issues.

**Comment by aalemayhu** [comment]
Reopening after triage: Open-in-Anki link is a clear in-scope QoL feature for Notion sync flow; closed without explicit decision.. Reviewed by: pm agent.

**Comment by aalemayhu** [comment]
The link back to Notion is supported via the "Add Notion link" card option, which adds an inline link on the back of each card so you can find the source note to update. Pick it from the card options before converting and it appears on every card. Closing this. If you're after a different link (e.g. a deep link into Anki itself), reopen with what you want it to do and where you want it to land.
