### ISSUE TITLE
fix: column list support for image on front and on back of Anki cards

### ISSUE THREAD

**Issue by leonwuk** [2anki/2anki.net#1146]
**Is your feature request related to a problem? Please describe.**

When I import the APKG to Anki it says: "unsupported column".

**Describe the solution you'd like**

I think there is something wrong with processing the column to create a flashcard. Would be nice if it could be checked if it is an easy fix.

**Describe alternatives you've considered**

Right now it is the only option to get images to the front and back of a card, which is really useful if you have a script from University or just in generell for flashcards. Only alternative right now is to create flashcards with text in the front and image in the back, which isn't too bad, but having images in the front and back makes it much nicer.

**Additional context**

**Comment by aalemayhu** [comment]
Thanks for reporting

**Comment by leonwuk** [comment]
Thank you so much man
