### ISSUE TITLE
feat: convert bulleted lists in HTML file to flashcards

### ISSUE THREAD

**Issue by themastermind48** [2anki/2anki.net#1165]
**Describe the bug**
Deck creation failed with file/rules. Kindly double-check your [settings](https://2anki.net/upload?view=template) or submit an issue on [GitHub](https://github.com/2anki/server/issues/new/choose), including an example for reference. Could not create a deck using your file and rules.

I have extracted the profile from Notion as HTML , and upload the ZIP ; it didn't work , I tried from another computer and account and the same error still appears

the notion page contains bullet-points , sub-bullet points and cloze-deletion (as code) words , wich the end result that I want .

**Screenshots**
the notion page which I want to convert into cloze-deletion flashcards :
![image](https://github.com/2anki/2anki.net/assets/135378087/a6d9d3a7-f724-4008-bc2f-65d8ad2d1cab)

the error that appears when upload the ZIP file:
![image](https://github.com/2anki/2anki.net/assets/135378087/8e202ab5-c113-46c1-8b4c-4e215ca90f3c)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [last version]

**Additional context**

**Comment by 22-modifier** [comment]
You are not setting up your notion page correctly if you want to use html upload. Only toggles work for HTML/zip file upload. 

If you want to use bullets, then you have to use the Notion API integration functionality. Example here: https://youtu.be/LqMiK2vGQ8Q

You may also have trouble given you also have numbered lists where you're trying to create cloze deletions as well as multiple tiers/levels of bullets. 

Lastly, if you want multiple cloze deletions on a single card, with HTML upload you have to use a toggle, then use Shift + Enter to get to new line in same card (and make sure you have setting on for multi-line toggles). I will sometimes do this and manually enter in the numbers for a numeric list with multiple cloze deletions.

**Comment by aalemayhu** [comment]
What do you guys think about adding the following rule in the HTML / zip file upload? If we don't detect any toggles than we check for bullet lists. This way this rule will only be triggered in the empty case and not introduce much friction to power users.

**Comment by aalemayhu** [comment]
Closed due to inactivity.

**Comment by aalemayhu** [comment]
Second-pass review (pm): TODO/stub found in relevant code - feature not fully implemented

Evidence: node_modules/.pnpm/aws-sdk@2.1693.0/node_modules/aws-sdk/clients/ssooidc.d.ts:113:     * The idToken is not implemented

**Comment by aalemayhu** [comment]
Closing — already implemented. Bulleted list conversion handled via `BlockBulletList.tsx` and `getListItems.tsx`.
