### ISSUE TITLE
Crypto is not defined

### ISSUE THREAD

**Issue by Birlinho** [2anki/2anki.net#1185]
**Describe the bug**
I export with Notion page as HTML and with subpages. I then drag them into the upload window in to Anki. Unfortunately I get the message: "Crypto is not defined". Unfortunately, the export then runs indefinitely. Are there currently problems with the export? The problem appears in every browser. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![grafik](https://github.com/2anki/2anki.net/assets/63461087/dec45273-eb3e-4562-a76d-3fecdf96bb1b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aalemayhu** [comment]
This has been resolved, thanks! If you still experience the issue, then re-open with steps to reproduce including a sample.
