### ISSUE TITLE
2anki can´t make flash cards out of my notion html file anymore

### ISSUE THREAD

**Issue by Lnacke** [2anki/2anki.net#1192]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lnacke** [comment]
![Bild_2023-06-28_140100164](https://github.com/2anki/2anki.net/assets/138011922/70a25623-3f63-49bb-818c-5d55331c412f)

**Comment by aalemayhu** [comment]
Second-pass review (pm): TODO/stub found in relevant code - feature not fully implemented

Evidence: src/services/ankify/ensureAnkifyModels.test.ts:9:  const stub = {
src/services/ankify/ensureAnkifyModels.test.ts:13:  re

**Comment by aalemayhu** [comment]
Closing this — stale 2023-24 ticket, no current repro and the surface has changed since. If the problem still happens, open a fresh issue with the Notion page (or file) and what went wrong.
