### ISSUE TITLE
How to Convert Notion Tables Into Anki Flashcards 

### ISSUE THREAD

**Issue by wsmmavis** [2anki/2anki.net#1291]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wsmmavis** [comment]
How to Convert Notion Tables Into Anki Flashcards 
I followed this YouTube tutorial (https://www.youtube.com/watch?v=xAKN8jwVlgw) to do, but it did not work.

**Comment by wsmmavis** [comment]
I downloaded the page as markdown&CSV and converted in to 2anki.net, it turns out: 
Deck creation failed with file/rules. Kindly double-check your [settings](https://2anki.net/upload?view=template) or submit an issue on [GitHub](https://github.com/2anki/server/issues/new/choose), including an example for reference. Could not create a deck using your file and rules.

**Comment by wsmmavis** [comment]
[Uploading f882dae7-20de-4ee1-9539-57d2b6e8bf25_Export-ff425d9c-4252-4139-ad89-bca07ec42acf.zip…]()

**Comment by aalemayhu** [comment]
In the video you are linking to. I am clearly using the builtin CSV import feature in the Anki desktop. Anki natively supports importing text files like spreadsheets and CSV: https://docs.ankiweb.net/importing/text-files.html?highlight=csv#spreadsheets-and-utf-8

When that is said, I do think we should have support for CSV since Notion does export it when you pick Markdown & CSV option. I will add CSV support and leave the Markdown details for a later date.

**Comment by aalemayhu** [comment]
@wsmmavis could you share a table example? I am not sure what support I want to add.

**Comment by aalemayhu** [comment]
Closed due to inactivity.

**Comment by aalemayhu** [comment]
Second-pass review (pm): TODO/stub found in relevant code - feature not fully implemented

Evidence: node_modules/.pnpm/@types+yargs@17.0.35/node_modules/@types/yargs/index.d.ts:886:    // not implemented: yargs decameliz

**Comment by aalemayhu** [comment]
This issue has no description beyond the blank feature-request template, so there's nothing specific to act on. Converting Notion tables is supported — export the Notion page as HTML and upload it, and table rows become cards. Closing as empty. Open a new issue with a sample export if a specific table doesn't convert the way you expect.
