### ISSUE TITLE
fix: toggle heading in file upload ignored

### ISSUE THREAD

**Issue by noelhoppe** [2anki/2anki.net#1292]
**Describe the bug**
2anki doesn't work if i put my .zip data in the converter an gives the error:
"Deck creation failed with file/rules. Kindly double-check your [settings](https://2anki.net/upload?view=template) or submit an issue on [GitHub](https://github.com/2anki/server/issues/new/choose), including an example for reference. Could not create a deck using your file and rules."

**To Reproduce**
1. Go to 'Notion Workspace'
2. Click on 'Export as HTML Data'
3. Go to 2anki
5. Upload the .zip data (Workspace in Notion contains images)

**Expected behavior**
I get a data that I can import in anki

**Desktop (please complete the following information):**
 - OS: [macOS Ventura 13.5.1]
 - Browser [chrome]
 - Version [Version 116.0.5845.179 (Offizieller Build) (arm64)]

**Comment by aalemayhu** [comment]
@noelhoppe I need a example to help you here. Are you uploading a database / table? A screenshot is also enough. I need a reproducer.

**Comment by noelhoppe** [comment]
Thanks for your help. I solved the  issue for myself. I formatted the page in Notion with toggle heading two instead of toggle and heading two instead of text. But maybe you can add this function later to anki.net.

**Comment by aalemayhu** [comment]
Thanks for info, updated the issue and will come back to it. It's unfortunately not so trivial due to the way Notion creates the HTML structure for the toggle headings. Maybe they changed since last time I checked.
