### ISSUE TITLE
Cloze flashcards bug

### ISSUE THREAD

**Issue by Noelia09** [2anki/2anki.net#1304]
When I export a notion file with toggles and block code to make cloze cards, your app only create falshcards to the toggles, but not for the code block so I can't see my cloze falshcards. I've tried creating a new notion file just with a cloze flashcards using the code block and whrn I try to upload it to your app it appears an error in the screen, saying that i should review my settings, but I have enable this options on my settings. It the first time I experience this problem, before I created some cloze flashcards without problems.

**Comment by aalemayhu** [comment]
Are you using the file upload? Are you using toggle headings? Have you tried without toggle headings and regular toggles?

**Comment by Noelia09** [comment]
I’m using  the file upload. I am not using  toggle headings. I know that toggle headings doesn’t work here. The problem is happening with regular toggles.

**Comment by Noelia09** [comment]
But when I create cloze flashcards I don’t use toggles I just add a block of text or bullets list

**Comment by aalemayhu** [comment]
Closed due to inactivity. Please re-open the issue with a proper example if still relevant.
