### ISSUE TITLE
Not allowing me to send my notion toggles into Anki flashcards

### ISSUE THREAD

**Issue by Laurencharlesworth** [2anki/2anki.net#1313]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aalemayhu** [comment]
Please provide more information. An example would be great.

**Comment by Laurencharlesworth** [comment]
Hello,
When I am transferring the Tig file across into the upload box it is saying not supported, however it is only toggles and I have not changed any settings from when it has previously worked,
Thank you,
Lauren Charlesworth

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aalemayhu** [comment]
I am not familiar with Tig files? We currently only support zip, html and partial support for Markdown / CSV.

**Comment by Laurencharlesworth** [comment]
Hi,
Yes html files for the tig on apple however it is still hdml, however it is not accepting the notion download onto anki at all it’s not letting me download my deck of cards, I have not changed any settings,
Thankyou
Lauren

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aalemayhu** [comment]
Please re-open the issue with a proper example. I don't understand your issue.
