### ISSUE TITLE
I can’t create Anki Cards with „2anki.net“. There is a big red popup

### ISSUE THREAD

**Issue by Hiiiiiiiiiiiiiikbkb** [2anki/2anki.net#1314]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aalemayhu** [comment]
Second-pass review (pm): TODO/stub found in relevant code - feature not fully implemented

Evidence: src/services/ankify/ensureAnkifyModels.test.ts:9:  const stub = {
src/services/ankify/ensureAnkifyModels.test.ts:13:  re

**Comment by aalemayhu** [comment]
This report contains only the blank bug-report template — no steps, no export file, and no error text — so there's nothing to reproduce. Closing as unactionable. If you still hit a red error popup on upload, open a new issue with the file you're converting and the exact message shown, and I'll take a look.
