### ISSUE TITLE
2anki stuck in loading file when I try to convert Notion page

### ISSUE THREAD

**Issue by filforce95** [2anki/2anki.net#1318]
Since a couple of days I have no chance to convert notion pages with toggles in it into anki packages. Normally I 

1. exported the Notion page I wanted to convert into anki cards in a zip file with html. 
2. Go to 2anki.net/upload
3. drag the file into the area for drag&drop
4. after a couple of seconds the finished apkg comes out.

Now this process stucks between step 3 and 4 and the loading circle runs without anything happens. I have reproduced this a couple of times and waited a lot.

**Screenshots**
![grafik](https://github.com/2anki/2anki.net/assets/49290121/7340b67e-0d27-485e-a26f-b770223dd468)
![grafik](https://github.com/2anki/2anki.net/assets/49290121/7d7ff2ff-23b2-41cb-afe1-d280865ba3c9)

**Desktop:**
 - OS: Linux
 - Browser firefox
 - Version 118.0.2 (64-Bit)

**Comment by filforce95** [comment]
[2023-10-10_ELEMa_export.zip](https://github.com/2anki/2anki.net/files/13113515/2023-10-10_ELEMa_export.zip)

yes, the issue was with this file. But later i changed to windows to check if it's the file. 
Under windows it was no problem to convert the file via 2anki in firefox

**Comment by filforce95** [comment]
There was no Issue on 2anki. 
The bug was there because uploading the file via an unsecure connection to 2anki with only http instead of https got blocked in my network.

So it was not the Issue i thought, but i think it would be better to redirect http automatically to https by 2anki.

**Comment by aalemayhu** [comment]
@filforce95 can you check again? Thanks!

**Comment by filforce95** [comment]
yes, i checked this right now.

![grafik](https://github.com/2anki/2anki.net/assets/49290121/ce90ae40-2fc9-440e-9087-3cc0b9eea36a)

when I go to "2anki.net/upload" I have only the http connection.
Then it is still not working.
FYI: I am on a university network with a firewall. I don't know if this has any influence on it, so just as additional information

**Comment by aalemayhu** [comment]
@filforce95 can you try again 😊 I missed some server configuration.

**Comment by filforce95** [comment]
Yes, I have. Now I was redirected and it works fine!

**Comment by aalemayhu** [comment]
Second-pass review (pm): TODO/stub found in relevant code - feature not fully implemented

Evidence: src/services/ankify/ensureAnkifyModels.test.ts:9:  const stub = {
src/services/ankify/ensureAnkifyModels.test.ts:13:  re

**Comment by aalemayhu** [comment]
Closing this — stale 2023-24 ticket, no current repro and the surface has changed since. If the problem still happens, open a fresh issue with the Notion page (or file) and what went wrong.
