### ISSUE TITLE
Notion to Anki does not work

### ISSUE THREAD

**Issue by Rupert1912** [2anki/2anki.net#1333]
Hey I have a problem. Somehow if I export my file it is a really long number with zip at the end. If I put this number in 2anki.net it's not creating a apkg file. It just creates the same long number with "Your decks-" in front of this number and Zip at the end. I don't know where my mistake is. Please help

**Comment by wernerkrauss** [comment]
If you export notion page with subpages, you create a zip file. 2Anki then creates a deck per page. Your decks should be in the generated zip file then.

I also had a hard time getting 2anki work yesterday; I read in #1324 that you need to export your pages as HTML, not markdown/csv! This helped me.

**Comment by aalemayhu** [comment]
I have created a fix for this. You can open the website via icognito to see the change. Alternatively just a until your browse will invalidate the cache.

**Comment by aalemayhu** [comment]
Second-pass review (engineer): Relevant code exists but no fix commit found

Evidence: code in: web/tests/mock-api.spec.ts
web/tests/rules-and-card-options.spec.ts
web/tests/ap

**Comment by aalemayhu** [comment]
Closing this — stale 2023-24 ticket, no current repro and the surface has changed since. If the problem still happens, open a fresh issue with the Notion page (or file) and what went wrong.
