### ISSUE TITLE
ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by Ohmann-tech** [2anki/2anki.net#1337]
**Describe the bug**
ENOSPC: no space left on device, write

**To Reproduce**
1. Go to homepage
2. Click on Get Started
3. Upload File
4. Error pops up

**Expected behavior**
Download of the .apkg

**Screenshots**
![image](https://github.com/2anki/2anki.net/assets/56092003/9bde52ef-2a64-4df7-b512-51ed0823ea64)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari and Firefox Developer Edition
 - Version Current One/Website

**Comment by Ohmann-tech** [comment]
Bug is not happening anymore. Closing.

**Comment by aalemayhu** [comment]
unfortunately this is still an issue. I have only fixed this post-mortem by restarting the server. It will come back again until the root cause has been resolved. I am not sure what is causing the disk running out of space since there is auto-deletion but maybe 21 minutes is too long with the current traffic.

**Comment by BCl920** [comment]
Issue still unsolved. Anyone an idea? Sorry for interrupting, but I strongly depend on this function... Got no idea by myself, I am no coder or something. Would be awesome to get some help <3 thx

**Comment by gafh7206** [comment]
i have the same problem but you can use this link for solve the problem https://ankiweb.net/shared/info/1940767534

**Comment by gafh7206** [comment]
i have the same problem i need help please.

**Comment by Schuchie** [comment]
Can confirm it. It's still an issue

**Comment by gafh7206** [comment]
how i can convert mi toggles in notion meanwhile? you know a way?

**Comment by zaarabbou** [comment]
having same Problem. Anyone can help?

**Comment by Mady-byte** [comment]
Same problem, since yesterday. Really need this function. I have enough storage on my PC.. Pls help if someone knows the anser, bc im really depending on it, thanks! :)

**Comment by aalemayhu** [comment]
The server should be up and running. I will hopefully get time to investigate what is going.

**Comment by Mady-byte** [comment]
I tried it and it works again, thank u so soo much!!

**Comment by BCl920** [comment]
Thank you very much for helping

**Comment by aalemayhu** [comment]
I have added a daily cron clean-up of the server. This should hopefully be enough to avoid this issue. Theoretically it's still possible for people to upload fast enough but let's leave that scenario for a later date.

**Comment by aalemayhu** [comment]
Second-pass review (pm): Maintainer indicated future intent but no resolution

Evidence: aalemayhu: I have added a daily cron clean-up of the server. This should hopefully be enoug
