### ISSUE TITLE
Export doesn't work anymore

### ISSUE THREAD

**Issue by LizCatL** [2anki/2anki.net#1347]
<img width="1469" alt="Bildschirmfoto 2023-11-18 um 13 26 46" src="https://github.com/2anki/2anki.net/assets/151374911/2ac9d96f-19c0-44c7-b4f7-63ea6843a9a5">

Must be a general problem, friends are having issues as well. When will it be fixed?

**Comment by mf338898** [comment]
> <img alt="Images de photo 2023-11-18 au 13 26 46" width="1469" src="https://user-images.githubusercontent.com/151374911/283998674-2ac9d96f-19c0-44c7-b4f7-63ea6843a9a5.png">
> Ce doit être un problème général, les amis ont également des problèmes. Quand sera-t-il réparé ?

I had this problem a couple of hours ago, but now everything's working properly again.

**Comment by aalemayhu** [comment]
Thanks for confirming, note that the storage issue is still not resolved. #1346 
I will hopefully get it fixed soon.
