### ISSUE TITLE
\sqrt functions invisible

### ISSUE THREAD

**Issue by MorgenmuffelLP** [2anki/2anki.net#1382]
Hey there, so i converted my cards through notion2anki, but i had the problem that the root functions arent visible, even though the \sqrt{} is in the code

does anyone know how to fix this? i dont want to fix each individual card
![math](https://github.com/2anki/2anki.net/assets/37043556/e2dbc9f5-0bbd-4d0a-9760-8db3c5e2a525)

**Comment by aalemayhu** [comment]
Someone asked the same thing on [Reddit](https://www.reddit.com/r/notion2anki/comments/18pyrvo/latex_sqrt_function_bugged/) . This is a bug, I will fix it.
