### ISSUE TITLE
code block cards not importing

### ISSUE THREAD

**Issue by hollypowell04** [2anki/2anki.net#1400]
**Describe the bug**
when I import the deck, only toggle cards are uploaded, any with code blocks in them are not

**To Reproduce**
export notion page as normal. upload to 2anki.net. open the apkg. only the toggle cards import.

**Expected behavior**
expected the code block cards to become cloze card, this has been functioning for me for a few months and has stopped working recently

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
thank you !

**Comment by aalemayhu** [comment]
Reopening after triage: Jan 2024 bug report that code-block toggles do not import; no won't-do reasoning given and code-block parsing is in scope.. Reviewed by: pm agent.

**Comment by aalemayhu** [comment]
Closing this — stale 2023-24 ticket, no current repro and the surface has changed since. If the problem still happens, open a fresh issue with the Notion page (or file) and what went wrong.
