### ISSUE TITLE
2Anki is always creating basic and reversed card

### ISSUE THREAD

**Issue by leonwuk** [2anki/2anki.net#1443]
I am using the Notion 2Anki integration not the file upload. Today I tried to convert a page into flash cards. There are always 2 cards created from one toggle and even from column lists, Basic and reverse. Even though it's not activated.

Don't know if that is just an issue for me, but maybe you can check it out.

**To Reproduce**
It is quite simple to reproduce, just convert a deck into flash cards.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.3.1
 - Browser Chrome, Safari

**Smartphone (please complete the following information):**

**Additional context**

**Comment by leonwuk** [comment]
For some reason it does work properly again. Thanks for creating such amazing tool, it's so helpful!

**Comment by leonwuk** [comment]
It does work properly again.

**Comment by aalemayhu** [comment]
Second-pass review (pm): TODO/stub found in relevant code - feature not fully implemented

Evidence: src/services/ankify/ensureAnkifyModels.test.ts:9:  const stub = {
src/services/ankify/ensureAnkifyModels.test.ts:13:  re
