### ISSUE TITLE
Handle reimports better

### ISSUE THREAD

**Issue by aalemayhu** [2anki/2anki.net#30]
Reimporting causes the cards to be duplicated. Either we should have deeper support with Notion and do uni or bi-directional synchronisation.

vd on Discord says: 
> (3) As a student, I will be adding more cards to my Notion file as I learn more things. It would be awesome if I could upload my new Notion file with extra cards and NotionToAnki can add only the new/updated cards to my Anki deck, so I don't have to go back and delete duplicates or create a new Notion file with only new cards just for export.

**Comment by scanf** [comment]
While this would save a bit of time it currently requires a lot more knowledge about the Anki and Notion database. Moving this out to a potential v2.

**Comment by aalemayhu** [comment]
Closing this as won't fix since Anki has improved the importing dialogue with several options now. If you are still effected by an issue related to imports please create a new issue with reproduce. 
<img width="748" alt="Screenshot 2024-04-13 at 8 49 38 PM" src="https://github.com/2anki/2anki.net/assets/925044/b03231a8-4d73-45f2-9ff1-d55e3746f5dd">
<img width="485" alt="Screenshot 2024-04-13 at 8 49 47 PM" src="https://github.com/2anki/2anki.net/assets/925044/6d6015c6-d5a7-423c-8fff-878cd6e390ed">
