### ISSUE TITLE
Allow overriding the font with web fonts

### ISSUE THREAD

**Issue by aalemayhu** [2anki/2anki.net#37]
https://fonts.google.com/

**Comment by scanf** [comment]
I am considering dropping this but will study the Notion pages and see how they are including the fonts and from where. Maybe we can just embed similar ones.

**Comment by aalemayhu** [comment]
There is an API and we can use it https://developers.google.com/fonts/docs/developer_api

**Comment by aalemayhu** [comment]
We might even make an Anki addon just for this.

**Comment by aalemayhu** [comment]
Nice to have
