### ISSUE TITLE
Full Support for Markdown & CSV Export

### ISSUE THREAD

**Issue by aalemayhu** [2anki/2anki.net#8]
There are bugs here and there but I feel like the Markdown support is getting there. For the CSV, I have not really used the tables so much so need to look into this in Notion.

**Comment by scanf** [comment]
The Markdown support has been abandoned, might reconsider later but for now and until v1 we are only HTML.

**Comment by aalemayhu** [comment]
I get a lot of emails from people using Markdown. We need to bring this support back.

**Comment by aalemayhu** [comment]
Partial support is in place but we still need to improve it.
