### ISSUE TITLE
Add support for external mailservers

### ISSUE THREAD

**Issue by NyasakiAT** [2anki/2anki.net#930]
**Is your feature request related to a problem? Please describe.**
When self hosting u may opt for not using mailgrid bc a external mail server is preferred

**Describe the solution you'd like**
use something like [smtp.js](https://hamzafarooq951.medium.com/send-e-mails-in-javascript-with-smtp-js-detailed-guide-5ab92cde7c49) to sent mails if sendgrid env var is not set and smtp env var is set
so the order in which 2anki handles mails: mailgrid -> smtp -> local mode

**Comment by aalemayhu** [comment]
I plan on removing the email API but thank you for the suggestion.

**Comment by aalemayhu** [comment]
Reopening after triage: SMTP support for self-hosters is in scope and labeled help-wanted; useful community signal.. Reviewed by: pm agent.

**Comment by aalemayhu** [comment]
This is a self-hosting request from 2022. The current product is hosted (2anki.net), uses SendGrid for transactional email, and isn't optimized for self-hosting. Swapping in arbitrary SMTP providers would add complexity nobody in the hosted product uses. I'm closing this — if a real fork ships with SMTP support, we can revisit then.
